/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSosRouteImport } from './routes/dashboard.sos'
import { Route as DashboardRosterRouteImport } from './routes/dashboard.roster'
import { Route as DashboardMyTasksRouteImport } from './routes/dashboard.my-tasks'
import { Route as DashboardMyShiftRouteImport } from './routes/dashboard.my-shift'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'
import { Route as DashboardAssignRouteImport } from './routes/dashboard.assign'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSosRoute = DashboardSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRosterRoute = DashboardRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyTasksRoute = DashboardMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyShiftRoute = DashboardMyShiftRouteImport.update({
  id: '/my-shift',
  path: '/my-shift',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignRoute = DashboardAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assign': typeof DashboardAssignRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/my-shift': typeof DashboardMyShiftRoute
  '/dashboard/my-tasks': typeof DashboardMyTasksRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assign': typeof DashboardAssignRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/my-shift': typeof DashboardMyShiftRoute
  '/dashboard/my-tasks': typeof DashboardMyTasksRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assign': typeof DashboardAssignRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/my-shift': typeof DashboardMyShiftRoute
  '/dashboard/my-tasks': typeof DashboardMyTasksRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/assign'
    | '/dashboard/assistant'
    | '/dashboard/emergency'
    | '/dashboard/map'
    | '/dashboard/my-shift'
    | '/dashboard/my-tasks'
    | '/dashboard/roster'
    | '/dashboard/sos'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/analytics'
    | '/dashboard/assign'
    | '/dashboard/assistant'
    | '/dashboard/emergency'
    | '/dashboard/map'
    | '/dashboard/my-shift'
    | '/dashboard/my-tasks'
    | '/dashboard/roster'
    | '/dashboard/sos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/assign'
    | '/dashboard/assistant'
    | '/dashboard/emergency'
    | '/dashboard/map'
    | '/dashboard/my-shift'
    | '/dashboard/my-tasks'
    | '/dashboard/roster'
    | '/dashboard/sos'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sos': {
      id: '/dashboard/sos'
      path: '/sos'
      fullPath: '/dashboard/sos'
      preLoaderRoute: typeof DashboardSosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roster': {
      id: '/dashboard/roster'
      path: '/roster'
      fullPath: '/dashboard/roster'
      preLoaderRoute: typeof DashboardRosterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-tasks': {
      id: '/dashboard/my-tasks'
      path: '/my-tasks'
      fullPath: '/dashboard/my-tasks'
      preLoaderRoute: typeof DashboardMyTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-shift': {
      id: '/dashboard/my-shift'
      path: '/my-shift'
      fullPath: '/dashboard/my-shift'
      preLoaderRoute: typeof DashboardMyShiftRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assign': {
      id: '/dashboard/assign'
      path: '/assign'
      fullPath: '/dashboard/assign'
      preLoaderRoute: typeof DashboardAssignRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAssignRoute: typeof DashboardAssignRoute
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMyShiftRoute: typeof DashboardMyShiftRoute
  DashboardMyTasksRoute: typeof DashboardMyTasksRoute
  DashboardRosterRoute: typeof DashboardRosterRoute
  DashboardSosRoute: typeof DashboardSosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAssignRoute: DashboardAssignRoute,
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMyShiftRoute: DashboardMyShiftRoute,
  DashboardMyTasksRoute: DashboardMyTasksRoute,
  DashboardRosterRoute: DashboardRosterRoute,
  DashboardSosRoute: DashboardSosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
